using System;
using System.Collections.Generic;
using System.Text;

namespace HeadyStudios
{/// <summary>
/// This is an account in which a user can manage their glass studio inventory and products
/// </summary>
    class UserAccount
    {
        private static int LastUserAccountNumber = 0;

        #region UserAccountProperties
        /// <summary>
        /// Email address of the user account
        /// </summary>
        public string EmailAddress { get; set; }
        /// <summary>
        /// Autogenerated number of the user account
        /// </summary>
        public int AccountNumber { get; }
        /// <summary>
        /// Date the user created account
        /// </summary>
        public DateTime DateCreated { get; }
        /// <summary>
        /// Quantity of 3mm Clear Rods
        /// </summary>
        public int ClearRod3mm { get; set; }
        /// <summary>
        /// Quantity of 14mm Clear Rods
        /// </summary>
        public int ClearRod14mm { get; set; }
        /// <summary>
        /// Quantity of Aqua Azual Rods
        /// </summary>
        public int AquaAzulRod { get; set; }

        #endregion

        #region Constructor
        /// <summary>
        /// Constructor creating unique AccountNumber and generating CreatedDate
        /// </summary>
        public UserAccount()
        {
            AccountNumber = ++LastUserAccountNumber;
            DateCreated = DateTime.Now;
        }

        #endregion

        #region Methods
        /// <summary>
        /// Enter quantity of 3mm Clear Rod in the Studio
        /// </summary>
        /// <param name="amount">Quantity of 3mm Clear Rod</param>
        public void Deposit3mm(int amount)
        {
            ClearRod3mm += amount;
        }

        /// <summary>
        /// Enter quantity of 14mm Clear Rod in the Studio
        /// </summary>
        /// <param name="amount">Quantity of 14mm Clear Rod</param>
        public void Deposit14mm(int amount)
        {
            ClearRod14mm += amount;
        }
        /// <summary>
        /// Enter quantity of Aqua Azul Rod in the Studio
        /// </summary>
        /// <param name="amount">Quantity of Aqua Azul</param>
        public void DepositAqua(int amount)
        {
            AquaAzulRod += amount;
        }


        #endregion
    }
}
